# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Google-ios-login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Google-ios-login
  pod 'AlertToast'
  pod 'SDWebImageSwiftUI'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'

  target 'Google-ios-loginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Google-ios-loginUITests' do
    # Pods for testing
  end

end
