# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyAppLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyAppLogin
  pod 'AlertToast'
  pod 'SDWebImageSwiftUI'
  pod 'GoogleSignIn'
  
  target 'MyAppLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAppLoginUITests' do
    # Pods for testing
  end

end
