# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp_Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp_Login
  pod 'AlertToast'
  pod 'SDWebImageSwiftUI'
  
  target 'MyApp_LoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyApp_LoginUITests' do
    # Pods for testing
  end

end
